# Generated by Django 4.2.7 on 2023-11-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='price',
        ),
        migrations.RemoveField(
            model_name='news',
            name='quantity',
        ),
    ]
